/* =====================================================================
   content.js  —  THE ONLY FILE YOU NEED TO EDIT
   ---------------------------------------------------------------------
   • News:        copy one line in `news`, paste at the TOP.
                  type = "Paper" | "Talk" | "Visit" | "Visitor" | "New member" | "Award"
   • Paper:       copy one { ... } block in `papers`, paste at the TOP.
                  selected: true  → shown under "Selected" (currently: your first-/last-author papers since 2024, plus TACL).
                  tags            → filter buttons are created automatically.
   • Person:      copy one { ... } block in `people`; put a square photo
                  in assets/people/ (any size, ~300px is plenty).
   • Project:     copy one block in `projects`.
   • Colours:     theme colours are "green" | "violet" | "amber" | "blue" | "rose" | "teal".
   • Unknown link → leave "" and it is hidden.  Simple HTML is allowed in text.
   ===================================================================== */

window.SITE = {

  /* ---------- Profile ---------- */
  name: "Yuxia Wang",
  nameNative: "王宇侠",
  highlightName: "Yuxia Wang",          // bolded automatically in author lists
  position: "Tenure-track Assistant Professor",
  affiliation: "INSAIT, Sofia University “St. Kliment Ohridski”",
  photo: "assets/photo.jpg",
  address: "Synergy Tower, Sofia Tech Park, blvd. Tsarigradsko shose 111R, 1784 Sofia, Bulgaria",
  lastUpdated: "September 2026",

  links: [
    { label: "Email",          url: "mailto:yuxia.wang@insait.ai" },
    { label: "Google Scholar", url: "https://scholar.google.com/citations?user=8MshEYoAAAAJ&hl=en" },
    { label: "X-NLP Lab",      url: "https://xnlp-lab.insait.ai/" },
    { label: "LinkedIn",       url: "https://www.linkedin.com/in/yuxia-wang-0220a72b1/" },
  ],

  bio: [
    `I am a tenure-track Assistant Professor at <a href="https://insait.ai/">INSAIT</a> in Sofia, where I lead the <a href="https://xnlp-lab.insait.ai/">X-NLP Lab</a>. Before that, I was a postdoctoral researcher in the MBZUAI NLP department, working with <a href="https://mbzuai.ac.ae/study/faculty/preslav-nakov/">Prof. Preslav Nakov</a>. I received my PhD from The University of Melbourne in January 2023, advised by <a href="https://eltimster.github.io/www/">Prof. Tim Baldwin</a> and <a href="https://www.rmit.edu.au/profiles/v/karin-verspoor">Prof. Karin Verspoor</a>, and my Bachelor's (2016) and Master's (2018) degrees from the Beijing Institute of Technology.`,
    `My research aims to make LLMs and agents helpful, safe, interpretable, and empathetic in their interactions with people. My work appears at ACL, EMNLP, NAACL, EACL, TACL, ICLR and NeurIPS.`,
  ],

  recruiting: {
    title: "Join us",
    text: `I am recruiting <b>PhD students, postdocs, research scientists, Master's thesis students and remote interns</b>. INSAIT offers yearly salaries of <b>€40,000</b> for PhD students, <b>€60,000</b> for postdocs and <b>€80,000</b> for research scientists, plus ample GPUs (GB200), and co-supervision with ETH Zurich and Google DeepMind. Send your CV to <a href="mailto:yuxia.wang@insait.ai">yuxia.wang@insait.ai</a>, together with and a short note on your research interests.`,
    link: "https://xnlp-lab.insait.ai/join.html",
    linkText: "Open positions",
  },

  /* ---------- Research directions ---------- */
  research: [
    { title: "Personal digital twins", color: "violet", icon: "twin",
      text: "Personalization and privacy protection, long-term memory and continual learning for models and agents." },
    { title: "Reliable AI and NLP", color: "green", icon: "shield",
      text: "LLM and agentic safety, fact-checking, uncertainty estimation, calibration and interpretability." },
    { title: "Diffusion language models", color: "amber", icon: "wave",
      text: "Going beyond autoregressive decoding, towards unified multimodal generation." },
    { title: "AI for finance and medicine", color: "blue", icon: "pulse",
      text: "Verifiable financial reasoning and medical fact verification." },
  ],

  /* ---------- Projects (from the lab's projects page) ---------- */
  projects: [
    { name: "Personal Digital Twins", status: "Ongoing", color: "violet",
      summary: "Two systems so far: <b>AI You</b>, a digital twin that captures a person's personality, skills and expertise, and <b>SlideLab</b>, part of a meeting proxy that attends meetings on your behalf. Next: the full meeting proxy, digital twins in education, and transparent user–agent interaction through animated, interactive decision making." },
    { name: "Trustworthy and Explainable AI", status: "Ongoing", color: "green",
      summary: "Trustworthy, explainable multimodal models and agents in medicine: uncertainty, calibration, interpretability and fairness." },
    { name: "LLM and Agentic Safety", status: "Ongoing", color: "rose",
      summary: "Safe behaviour in agentic systems under constraints and preferences; jailbreaks and defences for open-source LLMs." },
    { name: "Continual Learning", status: "Ongoing", color: "teal",
      summary: "Training-free and trainable approaches to continual learning for models and agents." },
    { name: "Bulgarian Language Processing", status: "Ongoing", color: "blue",
      summary: "Evaluating and improving Bulgarian language generation, with applications in education." },
    { name: "Empathy: Definition, Evaluation and Alignment", status: "Seeking collaborators", color: "amber",
      summary: "Empathy means different things across scenarios and people. We study it within multi-objective alignment alongside reasoning, factuality and safety." },
    { name: "Persona-aware Disambiguation in Long-term Memory", status: "Seeking collaborators", color: "violet",
      summary: "Ambiguity in persona-aware agents with long-term memory: scoping scenarios, defining tasks, building benchmarks and mitigations." },
    { name: "Safety Conditioned on Dynamic Constraints", status: "Seeking collaborators", color: "rose",
      summary: "Behaving safely under changing constraints from national regulations, domain policies, user preferences and authentication." },
  ],

  /* ---------- News (newest first) ---------- */
  newsShown: 6,
  news: [
    { date: "2026-09-30", type: "Visitor", text: "Zhuohan Xie (MBZUAI) visits and gives a talk on trustworthy financial AI." },
    { date: "2026-09-24", type: "Paper", text: "Two papers accepted to <b>NeurIPS 2026</b>, on temporal knowledge drift and layer-wise information for hallucination detection." },
    { date: "2026-09-21", type: "Visit", text: "Kick-off meeting of the EU Horizon <b>TWIN-X</b> project in Munich." },
    { date: "2026-09-15", type: "New member", text: "Donika Nakova Stefanova joins the lab as a visiting PhD student." },
    { date: "2026-09-08", type: "Paper", text: "Three papers accepted to <b>AACL 2026</b> (two main, one findings)." },
    { date: "2026-08-24", type: "Visitor", text: "Vilém Zouhar (ETH Zürich) visits and talks about efficient evaluation." },
    { date: "2026-08-21", type: "Paper", text: "Six papers accepted to <b>EMNLP 2026</b> (four main, two findings)." },
    { date: "2026-08-16", type: "Visitor", text: "Dr. Yue Feng (University of Birmingham) visits and talks about trustworthy LLM agents." },
    { date: "2026-06-15", type: "Visitor", text: "Dr. Lei You (DTU) visits and gives a talk, “Trust AI? Prove it.”" },
    { date: "2026-05-27", type: "Visit", text: "Visited the UKP Lab at TU Darmstadt with Kaiyang and gave talks." },
    { date: "2026-05-11", type: "Talk", text: "Talk at the ETH Zurich AI Center: <a href=\"https://ai.ethz.ch/research/events/academic-talks/details.when-do-language-models-fail-quietly-from-average-to-individual.77692.html\">When do language models fail quietly? From average to individual</a>." },
    { date: "2026-04-06", type: "Paper", text: "Five papers accepted to <b>ACL 2026</b> (four main, one findings)." },
    { date: "2026-03-16", type: "New member", text: "Jiayi Fu joins the lab as a PhD student." },
    { date: "2026-02-23", type: "Visit", text: "Attended the ELLIS 2026 NLP Workshop in Venice." },
    { date: "2026-01-26", type: "New member", text: "Kaiyang Wan joins the lab; his paper on a Fano-style accuracy bound for multi-hop reasoning is accepted to <b>ICLR 2026</b>." },
    { date: "2026-01-03", type: "Paper", text: "Two papers on machine-generated text and code detection accepted to <b>EACL 2026</b>." },
    { date: "2025-12-03", type: "Talk", text: "Talk at the ELLIS AI for Good webinar: <a href=\"https://www.youtube.com/live/J_gX9jDoQLE\">How we see AI to how AI sees us</a>." },
    { date: "2025-05-19", type: "Paper", text: "SpeechDialogueFactory accepted to <b>Interspeech 2025</b>." },
    { date: "2025-05-15", type: "Paper", text: "Seven papers accepted to <b>ACL 2025</b> (five main, two findings)." },
    { date: "2025-04-28", type: "Paper", text: "Three papers (Arabic safeguard evaluation, Libra-Leaderboard, FIRE) accepted to <b>NAACL 2025</b>." },
  ],

  /* ---------- Group ---------- */
  people: [
    { group: "Postdoc and PhD students", color: "green", members: [
      { name: "Yanda Li", role: "Postdoctoral Fellow", photo: "assets/people/yanda.jpg",
        interests: ["Personal Digital Twins", "AI for Medical"], url: "https://scholar.google.com/citations?user=12sQT1oAAAAJ" },
      { name: "Kaiyang Wan", role: "PhD Candidate", photo: "assets/people/kaiyang.jpg",
        interests: ["Interpretability", "Agents"], url: "https://kaiyangwan.github.io/" },
      { name: "Jiayi Fu", role: "PhD Candidate", photo: "assets/people/jiayi.jpg",
        interests: ["Diffusion LMs", "Continual Learning"], url: "https://poruna-byte.github.io/" },
      { name: "Asen Dotsinski", role: "PhD Candidate", photo: "assets/people/asen.jpg",
        interests: ["LLM Security", "Jailbreak Defences", "Mechanistic Interpretability"], url: "https://asendotsinski.github.io" },
      { name: "Donika Nakova Stefanova", role: "Visiting PhD", photo: "assets/people/donika.jpg",
        interests: ["Uncertainty & Calibration", "Agent Safety"], url: "" },
    ]},
    { group: "Explorers and summer interns", color: "amber", members: [
      { name: "Elena Dimitrova", role: "Explorer", photo: "assets/people/elena.jpg",
        interests: ["Bulgarian NLP", "AI for Education"], url: "" },
      { name: "Vanesa Kalinkova", role: "Explorer", photo: "assets/people/vanesa.jpg",
        interests: ["Bulgarian NLP", "LLM Evaluation"], url: "" },
      { name: "Emiliana Dimitrova", role: "SURF intern, MIT", photo: "assets/people/emiliana.jpg",
        interests: ["Multi-objective Alignment"], url: "" },
      { name: "Vasilije Ivanovic", role: "SURF intern, University of Belgrade", photo: "assets/people/vasilije.jpg",
        interests: ["Diffusion LMs"], url: "" },
    ]},
    { group: "Collaborating students", color: "violet", members: [
      { name: "Ruihong Zeng", role: "PhD, MBZUAI", photo: "assets/people/ruihong.jpg",
        interests: ["Memory", "Fact-checking"], url: "https://scholar.google.com/citations?user=hCt0gK0AAAAJ" },
      { name: "Hasan Iqbal", role: "PhD, MBZUAI", photo: "assets/people/hasan.jpg",
        interests: ["Fact-checking"], url: "https://scholar.google.com/citations?user=fP77klEAAAAJ" },
      { name: "Minh Ngoc Ta", role: "PhD, MBZUAI", photo: "assets/people/minh.jpg",
        interests: ["Clarifying Ambiguity", "Agents & Memory"], url: "https://scholar.google.com/citations?user=yfg2V6IAAAAJ" },
      { name: "Rania Elbadry", role: "PhD, MBZUAI", photo: "assets/people/rania.jpg",
        interests: ["Continual Learning", "AI for Finance"], url: "https://scholar.google.com/citations?user=ic1jai8AAAAJ" },
      { name: "Yan Lin", role: "PhD, Newcastle University", photo: "assets/people/linyan.jpg",
        interests: ["Agents", "AI for Finance"], url: "https://scholar.google.co.uk/citations?user=7skGGDUAAAAJ" },
      { name: "Yuyang Dai", role: "PhD, Florida State University", photo: "assets/people/yuyang.jpg",
        interests: ["Digital Twins", "Agents"], url: "https://scholar.google.com/citations?user=knQDa8IAAAAJ" },
      { name: "Xilong Cheng", role: "MSc, CUC", photo: "assets/people/xilong.jpg",
        interests: ["Role Playing", "Memory"], url: "https://ggbondcxl.github.io/" },
      { name: "Kanwal Mehreen", role: "MSc, University of British Columbia", photo: "assets/people/kanwal.jpg",
        interests: ["LLM Empathy"], url: "https://kanwal-mehreen.netlify.app/" },
      { name: "Junjie Liao", role: "Undergraduate, Beijing Normal University", photo: "assets/people/junjie.jpg",
        interests: ["Fact-checking"], url: "https://scholar.google.com/citations?user=lFwikWEAAAAJ" },
      { name: "Karun Sharma", role: "Undergraduate, Bennett University", photo: "assets/people/karun.jpg",
        interests: ["Meeting Proxy"], url: "https://anonymous-atom.github.io/" },
      { name: "Vidushee Vats", role: "Undergraduate, Bennett University", photo: "assets/people/vidushee.jpg",
        interests: ["Meeting Proxy"], url: "https://koookieee.github.io/" },
    ]},
  ],

  /* ---------- Teaching ---------- */
  teaching: [
    { code: "NLP 701 / 805", what: "Graduate-level Natural Language Processing", where: "MBZUAI", when: "2024–2025" },
    { code: "NLP 804", what: "PhD-level NLP Research Practice", where: "MBZUAI", when: "2024–2025" },
    { code: "UGRIP", what: "Undergraduate Research Internship Program, NLP project", where: "MBZUAI", when: "2024, 2025" },
  ],

  /* ---------- Paper ordering within a year ----------
     Papers are grouped by venue and the groups are ordered by the month the
     venue takes place (latest first). Add a venue here if you publish somewhere new.
     Use "VENUE YEAR" to override one specific year. Journals/preprints go last. */
  venueMonths: {
    "NeurIPS": 12, "AACL": 12, "EMNLP": 11, "WMT": 11, "BlackboxNLP": 11, "ClinicalNLP": 11,
    "INLG": 9, "Interspeech": 8, "CCKS": 8, "ACL": 7, "SemEval": 7, "IWSLT": 7, "BioNLP": 7,
    "EAMT": 6, "NAACL": 5, "ICLR": 4, "ECIR": 4, "EACL": 3, "COLING": 1, "GenAIDetect": 1,
    "COLING 2022": 10, "IWSLT 2022": 5, "NAACL 2024": 6,
    "TACL": -1, "JAIR": -1, "TAL Journal": -1, "PhD Thesis": -1, "arXiv": -2,
  },

  /* ---------- Publications (newest first) ---------- */
  papers: [
  { year: 2026, selected: false,
    title: "Right Frame, Wrong Rule: Cultural Cues Expose the Financial Knowledge Gap They Were Meant to Close",
    authors: "Rania Elbadry, Ahmed Heakl, Saeed Almheiri, Fan Zhang, Muhra AlMahri, Xueqing Peng, Mohsinul Kabir, Shuyao Wang, Yi Han, Saadeldine Eletter, Duzhen Zhang, Preslav Nakov, Yuxia Wang, Fajri Koto, Zhuohan Xie",
    venue: "EMNLP 2026 (Findings)", link: "",
    tags: ["Finance", "Multilingual"] },
  { year: 2026, selected: false,
    title: "MedRoundsQA: A Persona and Difficulty Aware Evaluation for Multi-Turn Medical Consultations",
    authors: "Youssef Mohamed, Ahmed Heakl, Qinrong Cui, Junhong Liang, Rafiq Ali, Bdour Babillie, …, Salman Khan, Imran Razzak, Yuxia Wang, Xiuying Chen",
    venue: "EMNLP 2026 (Main)", link: "https://arxiv.org/abs/2609.12851",
    tags: ["Clinical NLP"] },
  { year: 2026, selected: false,
    title: "Jais 2: A Family of Arabic-Centric Open Large Language Models",
    authors: "Mohamed Anwar, …, Yuxia Wang, …, et al. (60 authors)",
    venue: "EMNLP 2026 (Main)", link: "https://arxiv.org/abs/2608.13580",
    tags: ["Multilingual"] },
  { year: 2026, selected: false,
    title: "Stereotype Bias in a Bilingual Setting: A Culturally Grounded Evaluation in Kazakhstan",
    authors: "Nurkhan Laiyk, Daniil Orel, Ayana Mussabayeva, Maiya Goloburda, Kamila Kuishibekova, Liya Goloburda, …, Yuxia Wang, et al., Fajri Koto",
    venue: "ACL 2026", link: "https://aclanthology.org/2026.acl-long.598/",
    tags: ["Multilingual", "Fairness & Bias"] },
  { year: 2026, selected: true,
    title: "Is Human-Like Text Liked by Humans? Multilingual Human Detection and Preference Against AI",
    authors: "Yuxia Wang, Rui Xing, Jonibek Mansurov, Giovanni Puccetti, Zhuohan Xie, Minh Ngoc Ta, et al., Preslav Nakov",
    venue: "ACL 2026", link: "https://aclanthology.org/2026.acl-long.639/",
    tags: ["MGT Detection", "Multilingual"] },
  { year: 2026, selected: false,
    title: "FinChain: A Symbolic Benchmark for Verifiable Chain-of-Thought Financial Reasoning",
    authors: "Zhuohan Xie, Daniil Orel, Rushil Thareja, Dhruv Sahnan, Hachem Madmoun, Fan Zhang, …, Yuxia Wang, et al., Preslav Nakov",
    venue: "ACL 2026", link: "https://aclanthology.org/2026.acl-long.662/",
    tags: ["Finance", "Reasoning"] },
  { year: 2026, selected: false,
    title: "SAHM: A Benchmark for Arabic Financial and Shari’ah-Compliant Reasoning",
    authors: "Rania Elbadry, Sarfraz Ahmad, Ahmed Heakl, Dani Bouch, Momina Ahsan, Muhra AlMahri, …, Yuxia Wang, et al., Zhuohan Xie",
    venue: "ACL 2026", link: "https://aclanthology.org/2026.acl-long.1593/",
    tags: ["Finance", "Multilingual", "Reasoning"] },
  { year: 2026, selected: false,
    title: "FAID: Fine-grained AI-generated Text Detection using Multi-task Auxiliary and Multi-level Contrastive Learning",
    authors: "Minh Ngoc Ta, Dong Cao Van, Duc-Anh Hoang, Minh Le-Anh, Truong Nguyen, My Anh Tran Nguyen, Yuxia Wang, Preslav Nakov, Dinh Viet Sang",
    venue: "EACL 2026", link: "https://aclanthology.org/2026.eacl-long.151/",
    tags: ["MGT Detection"] },
  { year: 2026, selected: false,
    title: "AICD Bench: A Challenging Benchmark for AI-Generated Code Detection",
    authors: "Daniil Orel, Dilshod Azizov, Indraneil Paul, Yuxia Wang, Iryna Gurevych, Preslav Nakov",
    venue: "EACL 2026", link: "https://aclanthology.org/2026.eacl-long.325/",
    tags: ["MGT Detection"] },
  { year: 2026, selected: true,
    title: "RealFin: How Well Do LLMs Reason About Finance When Users Leave Things Unsaid?",
    authors: "Yuyang Dai, Yan Lin, Zhuohan Xie, Yuxia Wang",
    venue: "Findings of ACL 2026", link: "https://aclanthology.org/2026.findings-acl.1255/",
    tags: ["Finance", "Reasoning"] },
  { year: 2026, selected: false,
    title: "SemEval-2026 Task 13: Detecting Machine-Generated Code with Multiple Programming Languages, Generators, and Application Scenarios",
    authors: "Daniil Orel, Dilshod Azizov, Indraneil Paul, Yuxia Wang, Iryna Gurevych, Preslav Nakov",
    venue: "SemEval 2026", link: "https://aclanthology.org/2026.semeval-1.445/",
    tags: ["MGT Detection"] },
  { year: 2026, selected: true,
    title: "How Fine-Tuning Objectives Shape Layer-Wise Information in LLM Hallucination Detection",
    authors: "Kaiyang Wan, Forrest Sheng Bao, Amin Ahmad, Yuxia Wang",
    venue: "NeurIPS 2026", link: "",
    tags: ["Factuality", "Interpretability"] },
  { year: 2026, selected: false,
    title: "The Geometry of Forgetting: Temporal Knowledge Drift as an Independent Axis in LLM Representations",
    authors: "Rania Elbadry, Ahmed Heakl, Fan Zhang, Dani Bouch, Yuxia Wang, Preslav Nakov, Zhuohan Xie",
    venue: "NeurIPS 2026", link: "https://arxiv.org/pdf/2605.09195",
    tags: ["Interpretability"] },
  { year: 2026, selected: true,
    title: "Empathy Is Not the Scapegoat for Declines in Factuality and Reliability",
    authors: "Letian Shi*, Kanwal Mehreen*, Deheng Zhang, Yuxia Wang",
    venue: "AACL 2026 (Main)", link: "",
    tags: ["Factuality", "Empathy"] },
  { year: 2026, selected: true,
    title: "HALF: Harm-Aware LLM Fairness Evaluation Aligned with Deployment",
    authors: "Ali Mekky, Omar El Herraoui, Preslav Nakov, Yuxia Wang",
    venue: "AACL 2026 (Main)", link: "https://arxiv.org/pdf/2510.12217",
    tags: ["Safety"] },
  { year: 2026, selected: true,
    title: "MedSNIP: Building and Benchmarking Snippet-Level Granularity for Medical Fact Verification",
    authors: "Hasan Iqbal, Sarfraz Ahmad, Hyunjae Kim, Sihyeon Park, Junjie Liao, Qingyu Chen, Preslav Nakov, Yuxia Wang",
    venue: "EMNLP 2026 (Main)", link: "https://arxiv.org/pdf/2609.12884",
    tags: ["Factuality", "Clinical NLP"] },
  { year: 2026, selected: true,
    title: "Harm or Humor: A Multimodal, Multilingual Benchmark for Overt and Covert Harmful Humor",
    authors: "Ahmed Sharshar*, Hosam Elgendy*, Saad El Dine Ahmed, Yasser Rohaim, Yuxia Wang",
    venue: "EMNLP 2026 (Main)", link: "https://arxiv.org/pdf/2603.17759",
    tags: ["Safety", "Multilingual"] },
  { year: 2026, selected: true,
    title: "Retrieve Few, Verify Many: Segment-Level Evidence Reuse for Long-Form Factuality Assessment",
    authors: "Junjie Liao, Yuxia Wang",
    venue: "EMNLP 2026 (Findings)", link: "",
    tags: ["Factuality"] },
  { year: 2026, selected: false,
    title: "A Fano-style Accuracy Upper Bound for LLM Single-pass Reasoning in Multi-hop QA",
    authors: "Kaiyang Wan, Lang Gao, Honglin Mu, Preslav Nakov, Yuxia Wang, Xiuying Chen",
    venue: "ICLR 2026", link: "https://arxiv.org/pdf/2509.21199",
    tags: ["Reasoning"] },
  { year: 2025, selected: false,
    title: "Detection of Human and Machine-Authored Fake News in Urdu",
    authors: "Muhammad Zain Ali, Yuxia Wang, Bernhard Pfahringer, Tony C Smith",
    venue: "ACL 2025", link: "https://aclanthology.org/2025.acl-long.170/",
    tags: ["MGT Detection", "Multilingual"] },
  { year: 2025, selected: false,
    title: "HD-NDEs: Neural Differential Equations for Hallucination Detection in LLMs",
    authors: "Qing Li, Jiahui Geng, Zongxiong Chen, Derui Zhu, Yuxia Wang, Congbo Ma, Chenyang Lyu, Fakhri Karray",
    venue: "ACL 2025", link: "https://aclanthology.org/2025.acl-long.309/",
    tags: ["Factuality"] },
  { year: 2025, selected: false,
    title: "Explicit and Implicit Data Augmentation for Social Event Detection",
    authors: "Congbo Ma, Yuxia Wang, Jia Wu, Jian Yang, Jing Du, Zitai Qiu, Qing Li, Hu Wang, Preslav Nakov",
    venue: "ACL 2025", link: "https://aclanthology.org/2025.acl-long.412/",
    tags: ["Information Extraction"] },
  { year: 2025, selected: false,
    title: "KazMMLU: Evaluating Language Models on Kazakh, Russian, and Regional Knowledge of Kazakhstan",
    authors: "Mukhammed Togmanov, Nurdaulet Mukhituly, Diana Turmakhan, Jonibek Mansurov, Maiya Goloburda, Akhmed Sakip, …, Yuxia Wang, et al., Fajri Koto",
    venue: "ACL 2025", link: "https://aclanthology.org/2025.acl-long.701/",
    tags: ["Multilingual"] },
  { year: 2025, selected: false,
    title: "Instruction Tuning on Public Government and Cultural Data for Low-Resource Language: a Case Study in Kazakh",
    authors: "Nurkhan Laiyk, Daniil Orel, Rituraj Joshi, Maiya Goloburda, Yuxia Wang, Preslav Nakov, Fajri Koto",
    venue: "ACL 2025", link: "https://aclanthology.org/2025.acl-long.706/",
    tags: ["Multilingual"] },
  { year: 2025, selected: true,
    title: "OpenFactCheck: Building, Benchmarking Customized Fact-Checking Systems and Evaluating the Factuality of Claims and LLMs",
    authors: "Yuxia Wang, Minghan Wang, Hasan Iqbal, Georgi N. Georgiev, Jiahui Geng, Iryna Gurevych, Preslav Nakov",
    venue: "COLING 2025", link: "https://aclanthology.org/2025.coling-main.755/",
    tags: ["Factuality"] },
  { year: 2025, selected: false,
    title: "Loki: An Open-Source Tool for Fact Verification",
    authors: "Haonan Li, Xudong Han, Hao Wang, Yuxia Wang, Minghan Wang, Rui Xing, et al., Timothy Baldwin",
    venue: "COLING Demo 2025", link: "https://aclanthology.org/2025.coling-demos.4/",
    tags: ["Factuality"] },
  { year: 2025, selected: false,
    title: "FIRE: Fact-checking with Iterative Retrieval and Verification",
    authors: "Zhuohan Xie, Rui Xing, Yuxia Wang, Jiahui Geng, Hasan Iqbal, Dhruv Sahnan, Iryna Gurevych, Preslav Nakov",
    venue: "Findings of NAACL 2025", link: "https://aclanthology.org/2025.findings-naacl.158/",
    tags: ["Factuality"] },
  { year: 2025, selected: false,
    title: "VSCBench: Bridging the Gap in Vision-Language Model Safety Calibration",
    authors: "Jiahui Geng, Qing Li, Zongxiong Chen, Yuxia Wang, Derui Zhu, Zhuohan Xie, et al., Fakhri Karray",
    venue: "Findings of ACL 2025", link: "https://aclanthology.org/2025.findings-acl.158/",
    tags: ["Safety", "Uncertainty"] },
  { year: 2025, selected: false,
    title: "Qorgau: Evaluating Safety in Kazakh-Russian Bilingual Contexts",
    authors: "Maiya Goloburda, Nurkhan Laiyk, Diana Turmakhan, Yuxia Wang, Mukhammed Togmanov, Jonibek Mansurov, et al., Preslav Nakov",
    venue: "Findings of ACL 2025", link: "https://aclanthology.org/2025.findings-acl.507/",
    tags: ["Safety", "Multilingual"] },
  { year: 2025, selected: false,
    title: "UrduFactCheck: An Agentic Fact-Checking Framework for Urdu with Evidence Boosting and Benchmarking",
    authors: "Sarfraz Ahmad, Hasan Iqbal, Momina Ahsan, Numaan Naeem, Muhammad Ahsan Riaz Khan, Arham Riaz, Muhammad Arslan Manzoor, Yuxia Wang, Preslav Nakov",
    venue: "Findings of EMNLP 2025", link: "https://aclanthology.org/2025.findings-emnlp.1240/",
    tags: ["Factuality", "Multilingual"] },
  { year: 2025, selected: true,
    title: "UnsafeChain: Enhancing Reasoning Model Safety via Hard Cases",
    authors: "Raj Vardhan Tomar, Preslav Nakov, Yuxia Wang",
    venue: "IJCNLP-AACL 2025", link: "https://aclanthology.org/2025.findings-ijcnlp.75/",
    tags: ["Safety", "Reasoning"] },
  { year: 2025, selected: false,
    title: "GenAI Content Detection Task 1: English and Multilingual Machine-Generated Text Detection: AI vs. Human",
    authors: "Yuxia Wang, Artem Shelmanov, Jonibek Mansurov, Akim Tsvigun, Vladislav Mikhailov, Rui Xing, et al., Preslav Nakov",
    venue: "GenAIDetect Workshop 2025", link: "https://aclanthology.org/2025.genaidetect-1.27/",
    tags: ["MGT Detection", "Multilingual"] },
  { year: 2025, selected: false,
    title: "Conversational SimulMT: Efficient Simultaneous Translation with Large Language Models",
    authors: "Minghan Wang, Thuy-Trang Vu, Yuxia Wang, Ehsan Shareghi, Gholamreza Haffari",
    venue: "IWSLT 2025", link: "https://aclanthology.org/2025.iwslt-1.8/",
    tags: ["Machine Translation"] },
  { year: 2025, selected: false,
    title: "Arabic Dataset for LLM Safeguard Evaluation",
    authors: "Yasser Ashraf, Yuxia Wang, Bin Gu, Preslav Nakov, Timothy Baldwin",
    venue: "NAACL 2025", link: "https://aclanthology.org/2025.naacl-long.285/",
    tags: ["Safety", "Multilingual"] },
  { year: 2025, selected: false,
    title: "Libra-Leaderboard: Towards Responsible AI through a Balanced Leaderboard of Safety and Capability",
    authors: "Haonan Li, Xudong Han, Zenan Zhai, Honglin Mu, Hao Wang, Zhenxuan Zhang, …, Yuxia Wang, et al., Timothy Baldwin",
    venue: "NAACL Demo 2025", link: "https://aclanthology.org/2025.naacl-demo.23/",
    tags: ["Safety"] },
  { year: 2025, selected: false,
    title: "Overview of PAN 2025: Generative AI Detection, Multilingual Text Detoxification, Multi-Author Writing Style Analysis, and Generative Plagiarism Detection",
    authors: "Janek Bevendorff, Daryna Dementieva, Maik Frobe, Bela Gipp, Andre Greiner-Petter, Jussi Karlgren5 Maximilian Mayerl, et al.",
    venue: "ECIR 2025", link: "",
    tags: ["MGT Detection", "Multilingual"] },
  { year: 2025, selected: false,
    title: "Against The Achilles' Heel: A Survey on Red Teaming for Generative Models",
    authors: "Lizhi Lin, Honglin Mu, Zenan Zhai, Minghan Wang, Yuxia Wang, Renxi Wang, et al.",
    venue: "JAIR 2025", link: "",
    tags: ["Safety"] },
  { year: 2025, selected: false,
    title: "SpeechDialogueFactory: Generating High-Quality Speech Dialogue Data to Accelerate Your Speech-LLM Development",
    authors: "Minghan Wang, Ye Bai, Yuxia Wang, Thuy-Trang Vu, Ehsan Shareghi, Gholamreza Haffari",
    venue: "Interspeech 2025", link: "https://arxiv.org/abs/2503.23848",
    tags: ["Speech"] },
  { year: 2025, selected: false,
    title: "Llama-3.1-Sherkala-8B-Chat: An Open Large Language Model for Kazakh",
    authors: "Fajri Koto, Rituraj Joshi, Nurdaulet Mukhituly, Yuxia Wang, Zhuohan Xie, Rahul Pal, et al.",
    venue: "arXiv preprint", link: "https://arxiv.org/abs/2503.01493",
    tags: ["Multilingual"] },
  { year: 2025, selected: false,
    title: "A comprehensive survey of machine unlearning techniques for large language models",
    authors: "Jiahui Geng, Qing Li, Herbert Woisetschlaeger, Zongxiong Chen, Fengyu Cai, Yuxia Wang, et al., Fakhri Karray",
    venue: "arXiv preprint", link: "https://arxiv.org/abs/2503.01854",
    tags: ["Safety"] },
  { year: 2024, selected: true,
    title: "M4GT-Bench: Evaluation Benchmark for Black-Box Machine-Generated Text Detection",
    authors: "Yuxia Wang, Jonibek Mansurov, Petar Ivanov, Jinyan Su, Artem Shelmanov, Akim Tsvigun, et al., Preslav Nakov",
    venue: "ACL 2024", link: "https://aclanthology.org/2024.acl-long.218/",
    tags: ["MGT Detection"] },
  { year: 2024, selected: false,
    title: "Demystifying Instruction Mixing for Fine-tuning Large Language Models",
    authors: "Renxi Wang, Haonan Li, Minghao Wu, Yuxia Wang, Xudong Han, Chiyu Zhang, Timothy Baldwin",
    venue: "ACL SRW 2024", link: "https://aclanthology.org/2024.acl-srw.15/",
    tags: ["Reasoning"] },
  { year: 2024, selected: true,
    title: "M4: Multi-generator, Multi-domain, and Multi-lingual Black-Box Machine-Generated Text Detection",
    authors: "Yuxia Wang, Jonibek Mansurov, Petar Ivanov, Jinyan Su, Artem Shelmanov, Akim Tsvigun, et al., Preslav Nakov",
    venue: "EACL 2024", link: "https://aclanthology.org/2024.eacl-long.83/",
    tags: ["MGT Detection"] },
  { year: 2024, selected: true,
    title: "Factuality of Large Language Models: A Survey",
    authors: "Yuxia Wang, Minghan Wang, Muhammad Arslan Manzoor, Fei Liu, Georgi Nenkov Georgiev, Rocktim Jyoti Das, Preslav Nakov",
    venue: "EMNLP 2024", link: "https://aclanthology.org/2024.emnlp-main.1088/",
    tags: ["Factuality"] },
  { year: 2024, selected: false,
    title: "OpenFactCheck: A Unified Framework for Factuality Evaluation of LLMs",
    authors: "Hasan Iqbal, Yuxia Wang, Minghan Wang, Georgi Nenkov Georgiev, Jiahui Geng, Iryna Gurevych, Preslav Nakov",
    venue: "EMNLP Demo 2024", link: "https://aclanthology.org/2024.emnlp-demo.23/",
    tags: ["Factuality"] },
  { year: 2024, selected: false,
    title: "LLM-DetectAIve: a Tool for Fine-Grained Machine-Generated Text Detection",
    authors: "Mervat Abassy, Kareem Elozeiri, Alexander Aziz, Minh Ngoc Ta, Raj Vardhan Tomar, Bimarsha Adhikari, …, Yuxia Wang, et al., Preslav Nakov",
    venue: "EMNLP Demo 2024", link: "https://aclanthology.org/2024.emnlp-demo.35/",
    tags: ["MGT Detection"] },
  { year: 2024, selected: true,
    title: "Do-Not-Answer: Evaluating Safeguards in LLMs",
    authors: "Yuxia Wang, Haonan Li, Xudong Han, Preslav Nakov, Timothy Baldwin",
    venue: "Findings of EACL 2024", link: "https://aclanthology.org/2024.findings-eacl.61/",
    tags: ["Safety"] },
  { year: 2024, selected: true,
    title: "Rethinking STS and NLI in Large Language Models",
    authors: "Yuxia Wang, Minghan Wang, Preslav Nakov",
    venue: "Findings of EACL 2024", link: "https://aclanthology.org/2024.findings-eacl.65/",
    tags: ["Semantic Similarity"] },
  { year: 2024, selected: true,
    title: "A Chinese Dataset for Evaluating the Safeguards in Large Language Models",
    authors: "Yuxia Wang, Zenan Zhai, Haonan Li, Xudong Han, Shom Lin, Zhenxuan Zhang, Angela Zhao, Preslav Nakov, Timothy Baldwin",
    venue: "Findings of ACL 2024", link: "https://aclanthology.org/2024.findings-acl.184/",
    tags: ["Safety", "Multilingual"] },
  { year: 2024, selected: false,
    title: "Exploring the Potential of Multimodal LLM with Knowledge-Intensive Multimodal ASR",
    authors: "Minghan Wang, Yuxia Wang, Thuy-Trang Vu, Ehsan Shareghi, Reza Haf",
    venue: "Findings of EMNLP 2024", link: "https://aclanthology.org/2024.findings-emnlp.776/",
    tags: ["Speech"] },
  { year: 2024, selected: true,
    title: "Factcheck-Bench: Fine-Grained Evaluation Benchmark for Automatic Fact-checkers",
    authors: "Yuxia Wang, Revanth Gangi Reddy, Zain Muhammad Mujahid, Arnav Arora, Aleksandr Rubashevskii, Jiahui Geng, et al., Preslav Nakov",
    venue: "Findings of EMNLP 2024", link: "https://aclanthology.org/2024.findings-emnlp.830/",
    tags: ["Factuality"] },
  { year: 2024, selected: false,
    title: "Can Machines Resonate with Humans? Evaluating the Emotional and Empathic Comprehension of LMs",
    authors: "Muhammad Arslan Manzoor, Yuxia Wang, Minghan Wang, Preslav Nakov",
    venue: "Findings of EMNLP 2024", link: "https://aclanthology.org/2024.findings-emnlp.861/",
    tags: ["Empathy"] },
  { year: 2024, selected: false,
    title: "A Survey of Confidence Estimation and Calibration in Large Language Models",
    authors: "Jiahui Geng, Fengyu Cai, Yuxia Wang, Heinz Koeppl, Preslav Nakov, Iryna Gurevych",
    venue: "NAACL 2024", link: "https://aclanthology.org/2024.naacl-long.366/",
    tags: ["Uncertainty"] },
  { year: 2024, selected: true,
    title: "SemEval-2024 Task 8: Multidomain, Multimodel and Multilingual Machine-Generated Text Detection",
    authors: "Yuxia Wang, Jonibek Mansurov, Petar Ivanov, Jinyan Su, Artem Shelmanov, Akim Tsvigun, et al., Thomas Arnold",
    venue: "SemEval 2024", link: "https://aclanthology.org/2024.semeval-1.279/",
    tags: ["MGT Detection", "Multilingual"] },
  { year: 2023, selected: true,
    title: "Collective Human Opinions in Semantic Textual Similarity",
    authors: "Yuxia Wang, Shimin Tao, Ning Xie, Hao Yang, Timothy Baldwin, Karin Verspoor",
    venue: "TACL 2023", link: "https://aclanthology.org/2023.tacl-1.56/",
    tags: ["Uncertainty", "Semantic Similarity"] },
  { year: 2023, selected: false,
    title: "Towards Accurate and Reliable Modelling for Semantic Textual Similarity",
    authors: "Yuxia Wang",
    venue: "PhD Thesis, The University of Melbourne", link: "https://minerva-access.unimelb.edu.au/items/4e20a1c9-7e84-4cb9-a87e-a4153a90014c",
    tags: ["Semantic Similarity"] },
  { year: 2022, selected: false,
    title: "Noisy Label Regularisation for Textual Regression",
    authors: "Yuxia Wang, Timothy Baldwin, Karin Verspoor",
    venue: "COLING 2022", link: "https://aclanthology.org/2022.coling-1.371/",
    tags: ["Uncertainty"] },
  { year: 2022, selected: false,
    title: "Diformer: Directional Transformer for Neural Machine Translation",
    authors: "Minghan Wang, Jiaxin Guo, Yuxia Wang, Daimeng Wei, Hengchao Shang, Yinglu Li, et al., Hao Yang",
    venue: "EAMT 2022", link: "https://aclanthology.org/2022.eamt-1.11/",
    tags: ["Machine Translation"] },
  { year: 2022, selected: false,
    title: "Capture Human Disagreement Distributions by Calibrated Networks for Natural Language Inference",
    authors: "Yuxia Wang, Minghan Wang, Yimeng Chen, Shimin Tao, Jiaxin Guo, Chang Su, Min Zhang, Hao Yang",
    venue: "Findings of ACL 2022", link: "https://aclanthology.org/2022.findings-acl.120/",
    tags: ["Uncertainty"] },
  { year: 2022, selected: false,
    title: "The HW-TSC’s Offline Speech Translation System for IWSLT 2022 Evaluation",
    authors: "Yinglu Li, Minghan Wang, Jiaxin Guo, Xiaosong Qiao, Yuxia Wang, Daimeng Wei, et al., Ying Qin",
    venue: "IWSLT 2022", link: "https://aclanthology.org/2022.iwslt-1.20/",
    tags: ["Machine Translation", "Speech"] },
  { year: 2022, selected: false,
    title: "The HW-TSC’s Simultaneous Speech Translation System for IWSLT 2022 Evaluation",
    authors: "Minghan Wang, Jiaxin Guo, Yinglu Li, Xiaosong Qiao, Yuxia Wang, Zongyao Li, et al., Ying Qin",
    venue: "IWSLT 2022", link: "https://aclanthology.org/2022.iwslt-1.21/",
    tags: ["Machine Translation", "Speech"] },
  { year: 2022, selected: false,
    title: "The HW-TSC’s Speech to Speech Translation System for IWSLT 2022 Evaluation",
    authors: "Jiaxin Guo, Yinglu Li, Minghan Wang, Xiaosong Qiao, Yuxia Wang, Hengchao Shang, et al., Ying Qin",
    venue: "IWSLT 2022", link: "https://aclanthology.org/2022.iwslt-1.26/",
    tags: ["Machine Translation", "Speech"] },
  { year: 2022, selected: true,
    title: "Uncertainty Estimation and Reduction of Pre-trained Models for Text Regression",
    authors: "Yuxia Wang, Daniel Beck, Timothy Baldwin, Karin Verspoor",
    venue: "TACL 2022", link: "https://aclanthology.org/2022.tacl-1.39/",
    tags: ["Uncertainty"] },
  { year: 2021, selected: false,
    title: "How Length Prediction Influence the Performance of Non-Autoregressive Translation?",
    authors: "Minghan Wang, Guo Jiaxin, Yuxia Wang, Yimeng Chen, Su Chang, Hengchao Shang, Min Zhang, Shimin Tao, Hao Yang",
    venue: "BlackboxNLP 2021", link: "https://aclanthology.org/2021.blackboxnlp-1.14/",
    tags: ["Machine Translation"] },
  { year: 2021, selected: false,
    title: "HI-CMLM: Improve CMLM with Hybrid Decoder Input",
    authors: "Minghan Wang, Guo Jiaxin, Yuxia Wang, Yimeng Chen, Su Chang, Daimeng Wei, Min Zhang, Shimin Tao, Hao Yang",
    venue: "INLG 2021", link: "https://aclanthology.org/2021.inlg-1.16/",
    tags: ["Machine Translation"] },
  { year: 2021, selected: false,
    title: "HW-TSC’s Participation at WMT 2021 Quality Estimation Shared Task",
    authors: "Yimeng Chen, Chang Su, Yingtao Zhang, Yuxia Wang, Xiang Geng, Hao Yang, et al., Shujian Huang",
    venue: "WMT 2021", link: "https://aclanthology.org/2021.wmt-1.92/",
    tags: ["Machine Translation"] },
  { year: 2021, selected: false,
    title: "Incorporating complete syntactical knowledge for spoken language understanding",
    authors: "Shimin Tao, Ying Qin, Yimeng Chen, Chunning Du, Haifeng Sun, Weibin Meng, et al.",
    venue: "CCKS 2021", link: "",
    tags: ["Speech"] },
  { year: 2021, selected: false,
    title: "Joint-training on Symbiosis Networks for Deep Nueral Machine Translation models",
    authors: "Zhengzhe Yu, Jiaxin Guo, Minghan Wang, Daimeng Wei, Hengchao Shang, Zongyao Li, et al.",
    venue: "arXiv preprint", link: "https://arxiv.org/abs/2112.11642",
    tags: ["Machine Translation"] },
  { year: 2021, selected: false,
    title: "Self-distillation mixup training for non-autoregressive neural machine translation",
    authors: "Jiaxin Guo, Minghan Wang, Daimeng Wei, Hengchao Shang, Yuxia Wang, Zongyao Li, et al.",
    venue: "arXiv preprint", link: "https://arxiv.org/abs/2112.11640",
    tags: ["Machine Translation"] },
  { year: 2020, selected: false,
    title: "Evaluating the Utility of Model Configurations and Data Augmentation on Clinical Semantic Textual Similarity",
    authors: "Yuxia Wang, Fei Liu, Karin Verspoor, Timothy Baldwin",
    venue: "BioNLP Workshop 2020", link: "https://aclanthology.org/2020.bionlp-1.11/",
    tags: ["Semantic Similarity", "Clinical NLP"] },
  { year: 2020, selected: false,
    title: "Learning from Unlabelled Data for Clinical Semantic Textual Similarity",
    authors: "Yuxia Wang, Karin Verspoor, Timothy Baldwin",
    venue: "ClinicalNLP Workshop 2020", link: "https://aclanthology.org/2020.clinicalnlp-1.25/",
    tags: ["Semantic Similarity", "Clinical NLP"] },
  { year: 2020, selected: false,
    title: "A Multi-pass Sieve for Clinical Concept Normalization",
    authors: "Yuxia Wang, Brian Hur, Karin Verspoor, Timothy Baldwin",
    venue: "TAL Journal 2020", link: "https://aclanthology.org/2020.tal-2.3/",
    tags: ["Clinical NLP"] },
  ],
};
